title: Via Pasquale Circelli
resources:
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
  - url: /local/custom-lovelace/mini-media-player-bundle.js
    type: module
views:
  - title: default_view
    icon: mdi:home-modern
    badges:
      - device_tracker.applewaimiliano
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            name: Arcade
            entity: switch.cabinato_arcade
            icon: mdi:gamepad
            tap_action:
              action: toggle
          - type: entity-button
            name: Aspirapolvere
            entity: switch.presa_smart
            icon: mdi:robot-vacuum-variant
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: entity-button
            name: Stufa
            entity: switch.tuya_3
            icon: mdi:fire
            tap_action:
              action: toggle
          - type: entity-button
            name: Presa 4
            entity: switch.tuya_4
            icon: mdi:mdi:power-socket-eu
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: entity-button
            name: Tenda Luminosa
            entity: switch.tuya_5
            icon: mdi:led-outline
            tap_action:
              action: toggle
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.destra
          - type: picture-entity
            entity: camera.sinistra
      - type: glance
        title: Negozio
        show_state: false
        columns: 4
    #    show_header_toggle: False
        entities:
        #  - type: section
        #  - type: divider
          - entity: light.cassa
            tap_action:
              action: toggle
            hold_action:
              action: more-info
          - entity: light.fototessere
            tap_action:
              action: toggle
            hold_action:
              action: more-info
          - entity: light.vetrinetta
            tap_action:
              action: toggle
            hold_action:
              action: more-info
          - entity: light.ingresso
            tap_action:
              action: toggle
            hold_action:
              action: more-info
        #  - type: divider
          - binary_sensor.door_window_sensor_158d0001871594
          - binary_sensor.motion_sensor_158d00015b4de0
          - entity: light.hue_lightstrip_plus_1
            tap_action:
              action: toggle
            hold_action:
              action: more-info
          - entity: light.osram_led_esterno
            tap_action:
              action: toggle
            hold_action:
              action: more-info
  #luci di natale
  #        - entity: light.osram_switch
  #          tap_action:
  #            action: toggle
  #          hold_action:
  #            action: more-info
      - type: sensor
        entity: sensor.illumination_286c0788acc8
        name: Luminosità Ufficio
        graph: line
      - type: entities
        title: Ufficio
        show_header_toggle: False
        entities:
          - binary_sensor.door_window_sensor_158d00014d5609
          - binary_sensor.motion_sensor_158d00015e6c34
          - type: divider
          - light.postazione
          - light.assistenza
      - type: entities
        title: Studio Fotografico
        show_header_toggle: False
        entities:
          - light.luci_studio_fotografico
      - type: entities
        title: Corrente ed Internet
        show_header_toggle: False
        entities:
          - sensor.ups_input_voltage
          - sensor.ups_battery
          - sensor.ups_load
          - sensor.ups_status
          - sensor.ups_time_left
          - sensor.speedtest_download
          - sensor.speedtest_upload
      - type: custom:weather-card
        entity: weather.dark_sky
      - type: conditional
        conditions:
          - entity: switch.presa_smart
            state: "on"
        card:
          type: vertical-stack
          cards:
            - type: gauge
              name: Voltaggio
              unit: 'V'
              entity: sensor.tensione_aspirapolvere
              min: 200
              max: 260
              severity:
                green: 240
                yellow: 245
                red: 250
            - type: horizontal-stack
              cards:
                - type: gauge
                  name: Power
                  unit: 'W'
                  entity: sensor.consumo_istantaneo_aspirapolvere
                  min: 0
                  max: 50
                - type: gauge
                  name: Consumo
                  unit: 'KW/h'
                  entity: sensor.totale_energia_consumata_aspirapolvere
      - type: conditional
        conditions:
          - entity: switch.cabinato_arcade
            state: "on"
        card:
          type: vertical-stack
          cards:
            - type: gauge
              name: Voltaggio
              unit: 'V'
              entity: sensor.tensione_cabinato_arcade
              min: 200
              max: 260
              severity:
                green: 240
                yellow: 245
                red: 250
            - type: horizontal-stack
              cards:
                - type: gauge
                  name: Power
                  unit: 'W'
                  entity: sensor.consumo_istantaneo_cabinato_arcade
                  min: 0
                  max: 50
                - type: gauge
                  name: Consumo
                  unit: 'KW/h'
                  entity: sensor.totale_energia_consumata_cabinato_arcade
      - type: custom:mini-media-player
        entity: media_player.speaker
        artwork: cover
        artwork_border: true
        power: false
        group: true
        source: true
        progress: true
        shortcuts:
          columns: 3
          buttons:
            - name: DeeJay
              type: music
              id: http://radiodeejay-lh.akamaihd.net/i/RadioDeejay_Live_1@189857/master.m3u8
            - name: Capital
              type: music
              id: http://radiocapital-lh.akamaihd.net/i/RadioCapital_Live_1@196312/master.m3u8
            - name: m2o
              type: music
              id: http://radiom2o-lh.akamaihd.net/i/RadioM2o_Live_1@42518/master.m3u8
#Pagina dei consumi

  - title: Consumi
    icon: mdi:power
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Arcade
          - type: gauge
            name: Consumo Totale
            unit: 'KW/h'
            entity: sensor.totale_energia_consumata_cabinato_arcade
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Power
                unit: 'W'
                entity: sensor.consumo_istantaneo_cabinato_arcade
                min: 0
                max: 2200
                severity:
                  green: 0
                  yellow: 1000
                  red: 1800
              - type: gauge
                name: Voltaggio
                unit: 'V'
                entity: sensor.tensione_cabinato_arcade
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Aspirapolvere
          - type: gauge
            name: Consumo Totale
            unit: 'KW/h'
            entity: sensor.totale_energia_consumata_aspirapolvere
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Power
                unit: 'W'
                entity: sensor.consumo_istantaneo_aspirapolvere
                min: 0
                max: 2200
                severity:
                  green: 0
                  yellow: 1000
                  red: 1800
              - type: gauge
                name: Voltaggio
                unit: 'V'
                entity: sensor.tensione_aspirapolvere
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Stufa
          - type: gauge
            name: Consumo Totale
            unit: 'KW/h'
            entity: sensor.totale_energia_consumata_tuya3
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Power
                unit: 'W'
                entity: sensor.consumo_istantaneo_tuya3
                min: 0
                max: 2200
                severity:
                  green: 0
                  yellow: 1000
                  red: 1800
              - type: gauge
                name: Voltaggio
                unit: 'V'
                entity: sensor.tensione_tuya3
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Presa 4
          - type: gauge
            name: Consumo Totale
            unit: 'KW/h'
            entity: sensor.totale_energia_consumata_tuya4
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Power
                unit: 'W'
                entity: sensor.consumo_istantaneo_tuya4
                min: 0
                max: 2200
                severity:
                  green: 0
                  yellow: 1000
                  red: 1800
              - type: gauge
                name: Voltaggio
                unit: 'V'
                entity: sensor.tensione_tuya4
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Tenda Luminosa
          - type: gauge
            name: Consumo Totale
            unit: 'KW/h'
            entity: sensor.totale_energia_consumata_tuya5
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Power
                unit: 'W'
                entity: sensor.consumo_istantaneo_tuya5
                min: 0
                max: 2200
                severity:
                  green: 0
                  yellow: 1000
                  red: 1800
              - type: gauge
                name: Voltaggio
                unit: 'V'
                entity: sensor.tensione_tuya5

# Pagina Arcade

#  - title: Consumi
#    icon: mdi:gamepad
#    cards:
#      - type: conditional
#        conditions:
#          - entity: switch.cabinato_arcade
#            state: "on"
#        card:
#          type: iframe
#          url: http://192.168.3.17
#          aspect_ratio: 100%
