#Smart Plug Houzetek che controlla l'alimentazione del cabinato arcade
homeassistant:
sensor:
  - platform: mqtt
    name: "Totale energia consumata Cabinato Arcade"
    state_topic: "tele/vg/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Consumo Istantaneo Cabinato Arcade"
    state_topic: "tele/vg/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Tensione Cabinato Arcade"
    state_topic: "tele/vg/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Corrente Istantanea Cabinato Arcade"
    state_topic: "tele/vg/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

switch:
  - platform: mqtt
    name: "Cabinato Arcade"
    state_topic: "tele/vg/STATE"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/vg/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
