#Smart Plug Houzetek che controlla l'alimentazione dell'tuya3
homeassistant:
sensor:
  - platform: mqtt
    name: "Totale energia consumata tuya3"
    state_topic: "tele/tuya3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Consumo Istantaneo tuya3"
    state_topic: "tele/tuya3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Tensione tuya3"
    state_topic: "tele/tuya3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Corrente Istantanea tuya3"
    state_topic: "tele/tuya3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

switch:
  - platform: mqtt
    name: "Tuya 3"
    state_topic: "stat/tuya3/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/tuya3/POWER"
    availability_topic: "tele/tuya3/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
